### ISSUE TITLE
Dragon state on ParaView master

### ISSUE THREAD

**Issue by CharlesGueunet** [topology-tool-kit/ttk-data#72]
Using the latest TTK (91d38a0522342af312ce11fea8118f76e5549d4b) and ParaView master (3aa1b5818b4b724cac09aaf62114011869d90706) the dragon state file gives an invalid result:

![image](https://user-images.githubusercontent.com/5412579/131465009-5608c25f-0c25-4b7b-b2cd-c30216f2809f.png)

Changing the Upper/Lower Threshold in `Pairs` and `PersitenceThreshold` seems to fix the issue

**Comment by CharlesGueunet** [comment]
Error from another state (`nestedTrackingFromOverlap.py`) that may help:
```
(  33.088s) [paraview        ]    vtkOutputWindow.cxx:76     ERR| Traceback (most recent call last):
  File "/home/charles/Software/install/paraview/lib/python3.9/site-packages/paraview/servermanager.py", line 476, in __setattr__
    setter = getattr(self.__class__, name)
AttributeError: type object 'Threshold' has no attribute 'ThresholdRange'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 102, in <module>
  File "/home/charles/Software/install/paraview/lib/python3.9/site-packages/paraview/servermanager.py", line 482, in __setattr__
    _bc.setattr(self, name, value)
  File "/home/charles/Software/install/paraview/lib/python3.9/site-packages/paraview/_backwardscompatibilityhelper.py", line 397, in setattr
    raise NotSupportedException("The 'ThresholdRange' property has been "
paraview.NotSupportedException: The 'ThresholdRange' property has been removed in ParaView 5.10. Please set the lower and upper thresholds using the 'LowerThreshold' and 'UpperThreshold' properties, then set the 'ThresholdMethod' property to 'vtkThreshold.THRESHOLD_BETWEEN' to threshold between the lower and upper thresholds.
```

It seems state files should be updated accordingly :)

**Comment by julien-tierny** [comment]
has 5.10 been released yet?

**Comment by CharlesGueunet** [comment]
Not yet, but the release candidate is coming closer :)

**Comment by CharlesGueunet** [comment]
This seems to be ParaView related, not TTK. I will keep you in touch !

**Comment by CharlesGueunet** [comment]
That was a ParaView bug, now fixed :)
